// <auto-generated />
namespace IndieRadar.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ratingchangetablename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ratingchangetablename));
        
        string IMigrationMetadata.Id
        {
            get { return "201802241235420_rating change table name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
